name: TEST
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: install numpy
      run: pip3 install numpy
    - name: load qpSWIFT
      id: load-qpSWIFT
      uses: actions/cache@v3
      with:
        path: |
          ~/qpSWIFT
        key: qpSWIFT
    - if: ${{ steps.load-qpSWIFT.outputs.cache-hit != 'true' }}
      name: compile qpSWIFT
      run: |
        cd ~
        git clone https://github.com/qpSWIFT/qpSWIFT
        cd qpSWIFT
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        sudo cmake --build build --target install
    - name: install qpSWIFT python wrapper
      run: |
        cd ~/qpSWIFT/python
        sudo pip3 install numpy
        sudo python3 setup.py install
    - name: cache qpSWIFT
      id: cache-qpSWIFT
      uses: actions/cache/save@v3
      with:
        path: |
          ~/qpSWIFT
        key: qpSWIFT
    - name: test qpSWIFT
      run: |
        python3 ~/qpSWIFT/python/demoqp.py
        
#     - name: Setup upterm session
#       if: always()
#       if: failure()
#       uses: lhotari/action-upterm@v1
