name: TEST
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: load bpb
      id: bpb-load
      uses: actions/cache@v3
      with:
        path: |
          ~/betterpybullet
        key: bpb
    - if: ${{ steps.bpb-load.outputs.cache-hit != 'true' }}
      name: install pybullet
      continue-on-error: true
      run: |
        mkdir ~/betterpybullet
        cd betterpybullet
        git clone https://github.com/SemRoCo/bullet3.git
        cd bullet3
        ./build_better_pybullet.sh
    - name: cache bpb
      id: bpb-save
      uses: actions/cache/save@v3
      with:
        path: |
          ~/betterpybullet
        key: bpb
        
    - name: Setup upterm session
      if: always()
#       if: failure()
      uses: lhotari/action-upterm@v1
