name: TEST
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    strategy:
      matrix:
        qp_solver: [qpalm, qpSWIFT]
    env:
      QP_SOLVER: ${{ matrix.qp_solver }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8 - 3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt        
#       - name: Setup upterm session
#         if: always()
# #       if: failure()
#         uses: lhotari/action-upterm@v1
