name: TEST
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
#   push:
#     branches:
#       - master
#       - devel
#   pull_request:
#     branches:
#       - master
#       - devel
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: cache test
      id: muh
      uses: actions/cache@v3
      with:
        path: |
          ~/hi.txt
        key: muh
    - if: ${{ steps.muh.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: |
        echo asdf > hi.txt
    - name: touch
      run: |
        cat hi.txt
        
#    - name: Setup upterm session
##      if: always()
#      if: failure()
#      uses: lhotari/action-upterm@v1
