name: CI HSR standalone
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
      - devel
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: touch
      run: |
        touch hi.txt
  reuse:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
    - name: read
      run: |
        cat hi.txt
#    - name: Setup upterm session
##      if: always()
#      if: failure()
#      uses: lhotari/action-upterm@v1
