name: TEST
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: load casadi
      id: muh-load
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
        key: muh
    - if: ${{ steps.muh-load.outputs.cache-hit != 'true' }}
      name: install casadi
      continue-on-error: true
      run: |
        echo "cache miss"
        pip3 install casadi
    - name: cache muh
      id: muh-save
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.cache/pip
        key: muh
    - name: touch
      run: |
        pip3 freeze | grep casadi
        
    - name: Setup upterm session
      if: always()
#       if: failure()
      uses: lhotari/action-upterm@v1
